In [52]:
import pandas as pd

In [53]:
df = pd.read_csv("E:/py/datasets1/empdata.csv")
df

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [3]:
df.head()

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10

In [4]:
df.tail(2)

   empid           ename       sal         doj
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [5]:
df.shape

(6, 4)

In [6]:
df.columns

Index(['empid', 'ename', 'sal', 'doj'], dtype='object')

In [9]:
df['ename']

0        Ganesh Rao
1        Anil Kumar
2      Gaurav Gupta
3      Hema Chandra
4    Laxmi Prasanna
5         Anant Nag
Name: ename, dtype: object

In [10]:
df[['ename','sal']]

            ename       sal
0      Ganesh Rao  10000.00
1      Anil Kumar  23000.50
2    Gaurav Gupta  18000.33
3    Hema Chandra  16500.50
4  Laxmi Prasanna  12000.75
5       Anant Nag   9999.99

In [11]:
df[df['sal']>15000]

   empid         ename       sal         doj
1   1002    Anil Kumar  23000.50  2002-03-03
2   1003  Gaurav Gupta  18000.33  2002-03-03
3   1004  Hema Chandra  16500.50  2002-03-03

In [12]:
df[df['sal']<15000]

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [13]:
df[df['sal']== 23000.50]

   empid       ename      sal         doj
1   1002  Anil Kumar  23000.5  2002-03-03

In [14]:
df[df['doj']=='2002-03-03']

   empid         ename       sal         doj
1   1002    Anil Kumar  23000.50  2002-03-03
2   1003  Gaurav Gupta  18000.33  2002-03-03
3   1004  Hema Chandra  16500.50  2002-03-03

In [15]:
df.max()

empid              1006
ename    Laxmi Prasanna
sal             23000.5
doj          2002-03-03
dtype: object

In [16]:
df.min()

empid          1001
ename     Anant Nag
sal         9999.99
doj      1999-09-09
dtype: object

In [17]:
df.agg(min)

C:\Users\Amey\AppData\Local\Temp\ipykernel_15740\3584518614.py:1: FutureWarning: The provided callable <built-in function min> is currently using DataFrame.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.agg(min)

empid          1001
ename     Anant Nag
sal         9999.99
doj      1999-09-09
dtype: object

In [20]:
df[(df['sal']>12000) & (df['sal']<20000)]

   empid           ename       sal         doj
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10

In [22]:
df[(df['sal']>15000)&(df['doj']=='2002-03-03')]

   empid         ename       sal         doj
1   1002    Anil Kumar  23000.50  2002-03-03
2   1003  Gaurav Gupta  18000.33  2002-03-03
3   1004  Hema Chandra  16500.50  2002-03-03

In [23]:
df[(df['sal']>20000) | (df['sal']<12000)]

   empid       ename       sal         doj
0   1001  Ganesh Rao  10000.00  2000-10-10
1   1002  Anil Kumar  23000.50  2002-03-03
5   1006   Anant Nag   9999.99  1999-09-09

In [24]:
df["doj"] = pd.to_datetime(df["doj"])

In [25]:
df

   empid           ename       sal        doj
0   1001      Ganesh Rao  10000.00 2000-10-10
1   1002      Anil Kumar  23000.50 2002-03-03
2   1003    Gaurav Gupta  18000.33 2002-03-03
3   1004    Hema Chandra  16500.50 2002-03-03
4   1005  Laxmi Prasanna  12000.75 2000-08-10
5   1006       Anant Nag   9999.99 1999-09-09

In [54]:
df

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [61]:
print(df['doj'].dtype)

object

In [62]:
df['doj'] = pd.to_datetime(df['doj'])

In [66]:
df['year'] = df['doj'].dt.year

df

   empid           ename       sal        doj  year
0   1001      Ganesh Rao  10000.00 2000-10-10  2000
1   1002      Anil Kumar  23000.50 2002-03-03  2002
2   1003    Gaurav Gupta  18000.33 2002-03-03  2002
3   1004    Hema Chandra  16500.50 2002-03-03  2002
4   1005  Laxmi Prasanna  12000.75 2000-08-10  2000
5   1006       Anant Nag   9999.99 1999-09-09  1999

In [67]:
df[df['year']== 2002]

   empid         ename       sal        doj  year
1   1002    Anil Kumar  23000.50 2002-03-03  2002
2   1003  Gaurav Gupta  18000.33 2002-03-03  2002
3   1004  Hema Chandra  16500.50 2002-03-03  2002

In [73]:
df['doj'].min() 
df.loc[df['doj'].idxmin()]

empid                   1006
ename              Anant Nag
sal                  9999.99
doj      1999-09-09 00:00:00
year                    1999
Name: 5, dtype: object

In [74]:
df.loc[df['doj'].idxmax()]

empid                   1002
ename             Anil Kumar
sal                  23000.5
doj      2002-03-03 00:00:00
year                    2002
Name: 1, dtype: object

In [81]:
df['day']= df['doj'].dt.day
df

   empid           ename       sal        doj  year        date  day
0   1001      Ganesh Rao  10000.00 2000-10-10  2000  2000-10-10   10
1   1002      Anil Kumar  23000.50 2002-03-03  2002  2002-03-03    3
2   1003    Gaurav Gupta  18000.33 2002-03-03  2002  2002-03-03    3
3   1004    Hema Chandra  16500.50 2002-03-03  2002  2002-03-03    3
4   1005  Laxmi Prasanna  12000.75 2000-08-10  2000  2000-08-10   10
5   1006       Anant Nag   9999.99 1999-09-09  1999  1999-09-09    9

In [85]:
df[today] = pd.Timestamp.today()
today

Timestamp('2026-09-02 18:36:19.133793')

In [88]:
df['doj'] = pd.to_datetime(df['doj'])

df['today'] = pd.Timestamp.today()

df['years_of_exp'] = (df['today'] - df['doj']).dt.days // 365

df[['doj', 'today', 'years_of_exp']]

         doj                      today  years_of_exp
0 2000-10-10 2026-09-02 18:43:46.784829            25
1 2002-03-03 2026-09-02 18:43:46.784829            24
2 2002-03-03 2026-09-02 18:43:46.784829            24
3 2002-03-03 2026-09-02 18:43:46.784829            24
4 2000-08-10 2026-09-02 18:43:46.784829            26
5 1999-09-09 2026-09-02 18:43:46.784829            27

In [89]:
df["department"] = ["DE", "QA", "DE", "HR", "QA", "DE"]
df

,empid,ename,sal,doj,year,date,day,2026-09-02 18:36:19.133793,today,years_of_exp,department
0,1001,Ganesh Rao,10000.00,2000-10-10,2000,2000-10-10,10,2026-09-02 18:39:22.853443,2026-09-02 18:43:46.784829,25,DE
1,1002,Anil Kumar,23000.50,2002-03-03,2002,2002-03-03,3,2026-09-02 18:39:22.853443,2026-09-02 18:43:46.784829,24,QA
2,1003,Gaurav Gupta,18000.33,2002-03-03,2002,2002-03-03,3,2026-09-02 18:39:22.853443,2026-09-02 18:43:46.784829,24,DE
3,1004,Hema Chandra,16500.50,2002-03-03,2002,2002-03-03,3,2026-09-02 18:39:22.853443,2026-09-02 18:43:46.784829,24,HR
4,1005,Laxmi Prasanna,12000.75,2000-08-10,2000,2000-08-10,10,2026-09-02 18:39:22.853443,2026-09-02 18:43:46.784829,26,QA
5,1006,Anant Nag,9999.99,1999-09-09,1999,1999-09-09,9,2026-09-02 18:39:22.853443,2026-09-02 18:43:46.784829,27,DE

In [94]:
df.groupby('department')['sal'].mean()

department
DE    12666.773333
HR    16500.500000
QA    17500.625000
Name: sal, dtype: float64

In [97]:
df.groupby('department')['sal'].agg(['max','min','mean'])

                 max       min          mean
department
DE          18000.33   9999.99  12666.773333
HR          16500.50  16500.50  16500.500000
QA          23000.50  12000.75  17500.625000

In [99]:
df.groupby('department').size()

department
DE    3
HR    1
QA    2
dtype: int64

In [102]:
df.loc[df.groupby('department')['sal'].idxmax()]

,empid,ename,sal,doj,year,date,day,2026-09-02 18:36:19.133793,today,years_of_exp,department
2,1003,Gaurav Gupta,18000.33,2002-03-03,2002,2002-03-03,3,2026-09-02 18:39:22.853443,2026-09-02 18:43:46.784829,24,DE
3,1004,Hema Chandra,16500.50,2002-03-03,2002,2002-03-03,3,2026-09-02 18:39:22.853443,2026-09-02 18:43:46.784829,24,HR
1,1002,Anil Kumar,23000.50,2002-03-03,2002,2002-03-03,3,2026-09-02 18:39:22.853443,2026-09-02 18:43:46.784829,24,QA

In [106]:
df.loc[df['sal']>15000,['sal']]

        sal
1  23000.50
2  18000.33
3  16500.50

In [109]:
df.iloc[0:3,9:11]

   years_of_exp department
0            25         DE
1            24         QA
2            24         DE

In [110]:
df.query('sal>15000')

,empid,ename,sal,doj,year,date,day,2026-09-02 18:36:19.133793,today,years_of_exp,department
1,1002,Anil Kumar,23000.50,2002-03-03,2002,2002-03-03,3,2026-09-02 18:39:22.853443,2026-09-02 18:43:46.784829,24,QA
2,1003,Gaurav Gupta,18000.33,2002-03-03,2002,2002-03-03,3,2026-09-02 18:39:22.853443,2026-09-02 18:43:46.784829,24,DE
3,1004,Hema Chandra,16500.50,2002-03-03,2002,2002-03-03,3,2026-09-02 18:39:22.853443,2026-09-02 18:43:46.784829,24,HR

In [117]:
df['sal_rank']= df['sal'].rank(ascending=False)
df['sal_rank']

0    5.0
1    1.0
2    2.0
3    3.0
4    4.0
5    6.0
Name: sal_rank, dtype: float64

In [121]:
df['prv_sala']= df['sal'].shift()
df['salary_difference'] = df['sal'] - df['prv_sala']
df[['sal','prv_sala','salary_difference']]

        sal  prv_sala  salary_difference
0  10000.00       NaN                NaN
1  23000.50  10000.00           13000.50
2  18000.33  23000.50           -5000.17
3  16500.50  18000.33           -1499.83
4  12000.75  16500.50           -4499.75
5   9999.99  12000.75           -2000.76

In [123]:
df['cumulative_salary']=df['sal'].cumsum()
df[['sal','cumulative_salary']] #total_sal as moving down the row

        sal  cumulative_salary
0  10000.00           10000.00
1  23000.50           33000.50
2  18000.33           51000.83
3  16500.50           67501.33
4  12000.75           79502.08
5   9999.99           89502.07

In [149]:
df['department_avg_salary']=df.groupby('department')['sal'].agg('mean')
df['department_avg_salary']

#This does not work correctly for assigning back to every employee because agg() returns one value per department.

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: department_avg_salary, dtype: float64

In [127]:
df['department_avg_salary_trans'] = df.groupby('department')['sal'].transform('mean')
df['department_avg_salary_trans']

0    12666.773333
1    17500.625000
2    12666.773333
3    16500.500000
4    17500.625000
5    12666.773333
Name: department_avg_salary_trans, dtype: float64

In [129]:
#to check missing val from rows 
df.isnull()
df.isnull().sum()

empid                          0
ename                          0
sal                            0
doj                            0
year                           0
date                           0
day                            0
2026-09-02 18:36:19.133793     0
today                          0
years_of_exp                   0
department                     0
sal_rank                       0
prv_sala                       1
salary_difference              1
cumulative_salary              0
department_avg_salary          6
department_avg_salary_trans    0
dtype: int64

In [131]:
#checking Duplicate employee IDs 
df['empid'].duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
Name: empid, dtype: bool

In [132]:
#check duplicate complete rows 
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [empid, ename, sal, doj, year, date, day, 2026-09-02 18:36:19.133793, today, years_of_exp, department, sal_rank, prv_sala, salary_difference, cumulative_salary, department_avg_salary, department_avg_salary_trans]
Index: []

In [133]:
df.dtypes

empid                                   int64
ename                                  object
sal                                   float64
doj                            datetime64[ns]
year                                    int32
date                                   object
day                                     int32
2026-09-02 18:36:19.133793     datetime64[us]
today                          datetime64[us]
years_of_exp                            int64
department                             object
sal_rank                              float64
prv_sala                              float64
salary_difference                     float64
cumulative_salary                     float64
department_avg_salary                 float64
department_avg_salary_trans           float64
dtype: object

In [135]:
quality_report = pd.DataFrame({
    'missing_val':df.isnull().sum(),
    'data_type':df.dtypes,
    'unique_value':df.nunique()
})
quality_report

                             missing_val       data_type  unique_value
empid                                  0           int64             6
ename                                  0          object             6
sal                                    0         float64             6
doj                                    0  datetime64[ns]             4
year                                   0           int32             3
date                                   0          object             4
day                                    0           int32             3
2026-09-02 18:36:19.133793             0  datetime64[us]             1
today                                  0  datetime64[us]             1
years_of_exp                           0           int64             4
department                             0          object             3
sal_rank                               0         float64             6
prv_sala                               1         float64             5
salary_difference                      1         float64             5
cumulative_salary                      0         float64             6
department_avg_salary                  6         float64             0
department_avg_salary_trans            0         float64             3

In [137]:
print("Duplicate Employee IDs:", df['empid'].duplicated().sum())
print("Duplicate Complete Rows:", df.duplicated().sum())

Duplicate Employee IDs: 0
Duplicate Complete Rows: 0

In [139]:
df['empid'].duplicated().sum()

np.int64(0)

In [142]:
df['sal'].mean()

np.float64(14917.011666666667)

In [144]:
df['sal'] = df['sal'].fillna(df['sal'].mean())
df['sal']

0    10000.00
1    23000.50
2    18000.33
3    16500.50
4    12000.75
5     9999.99
Name: sal, dtype: float64

In [148]:
df['salary_category'] = df['sal'].apply(
    lambda x: 'High' if x >= 50000 else 'Low'
)
df['salary_category']

0    Low
1    Low
2    Low
3    Low
4    Low
5    Low
Name: salary_category, dtype: object