In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("E:/py/datasets1/empdata.csv")
df

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [9]:
df['new_sal']=df['sal'].map(lambda x: x+(x*15/100))
df['new_sal']
df

   empid           ename       sal         doj     new_sal
0   1001      Ganesh Rao  10000.00  2000-10-10  11500.0000
1   1002      Anil Kumar  23000.50  2002-03-03  26450.5750
2   1003    Gaurav Gupta  18000.33  2002-03-03  20700.3795
3   1004    Hema Chandra  16500.50  2002-03-03  18975.5750
4   1005  Laxmi Prasanna  12000.75  2000-08-10  13800.8625
5   1006       Anant Nag   9999.99  1999-09-09  11499.9885

In [14]:
def salary_category(x):
    if x>25000:
        return 'high'
    elif x>15000:
        return 'medium'
    else:
        return 'low'

df['sal_cat']=df['sal'].apply(salary_category)
df

   empid           ename       sal         doj     new_sal sal_cat
0   1001      Ganesh Rao  10000.00  2000-10-10  11500.0000     low
1   1002      Anil Kumar  23000.50  2002-03-03  26450.5750  medium
2   1003    Gaurav Gupta  18000.33  2002-03-03  20700.3795  medium
3   1004    Hema Chandra  16500.50  2002-03-03  18975.5750  medium
4   1005  Laxmi Prasanna  12000.75  2000-08-10  13800.8625     low
5   1006       Anant Nag   9999.99  1999-09-09  11499.9885     low

In [18]:
def uppercase(x):
    return x.upper()
df['name_mapper']=df['ename'].map(uppercase)
df

,empid,ename,sal,doj,new_sal,sal_cat,name_mapper
0,1001,Ganesh Rao,10000.00,2000-10-10,11500.0000,low,GANESH RAO
1,1002,Anil Kumar,23000.50,2002-03-03,26450.5750,medium,ANIL KUMAR
2,1003,Gaurav Gupta,18000.33,2002-03-03,20700.3795,medium,GAURAV GUPTA
3,1004,Hema Chandra,16500.50,2002-03-03,18975.5750,medium,HEMA CHANDRA
4,1005,Laxmi Prasanna,12000.75,2000-08-10,13800.8625,low,LAXMI PRASANNA
5,1006,Anant Nag,9999.99,1999-09-09,11499.9885,low,ANANT NAG

In [20]:
avg_sala= df['sal'].mean()

def avg_sal(x):
    if x>avg_sala:
        return 'Above avg'
    else:
        return'below avg'
    
df['salary_status']=df['sal'].apply(avg_sal)
df

,empid,ename,sal,doj,new_sal,sal_cat,name_mapper,salary_status
0,1001,Ganesh Rao,10000.00,2000-10-10,11500.0000,low,GANESH RAO,below avg
1,1002,Anil Kumar,23000.50,2002-03-03,26450.5750,medium,ANIL KUMAR,Above avg
2,1003,Gaurav Gupta,18000.33,2002-03-03,20700.3795,medium,GAURAV GUPTA,Above avg
3,1004,Hema Chandra,16500.50,2002-03-03,18975.5750,medium,HEMA CHANDRA,Above avg
4,1005,Laxmi Prasanna,12000.75,2000-08-10,13800.8625,low,LAXMI PRASANNA,below avg
5,1006,Anant Nag,9999.99,1999-09-09,11499.9885,low,ANANT NAG,below avg

In [22]:
data = {
    "emp": ["A", "A", "B", "B", "C", "C"],
    "month": ["Jan", "Feb", "Jan", "Feb", "Jan", "Feb"],
    "sales": [100, 200, 300, 400, 500, 600]
}
df = pd.DataFrame(data)
df

  emp month  sales
0   A   Jan    100
1   A   Feb    200
2   B   Jan    300
3   B   Feb    400
4   C   Jan    500
5   C   Feb    600

In [28]:
result =df.pivot(
    index='emp',
    columns='month',
    values='sales'
)
print(result)

month  Feb  Jan
emp
A      200  100
B      400  300
C      600  500

In [30]:
data = {
    "department": ["DE", "DE", "DE", "QA", "QA", "HR"],
    "employee": ["A", "B", "C", "D", "E", "F"],
    "salary": [50000, 60000, 70000, 40000, 50000, 45000]
}
df=pd.DataFrame(data)
df

  department employee  salary
0         DE        A   50000
1         DE        B   60000
2         DE        C   70000
3         QA        D   40000
4         QA        E   50000
5         HR        F   45000

In [32]:
result= df.pivot_table(
    index='department', #rows
    values='salary', #column to calculate 
    aggfunc='mean'  #avg
)

print(result)

             salary
department
DE          60000.0
HR          45000.0
QA          45000.0

In [33]:
result= df.pivot_table(
    index='department', #rows
    values='salary', #column to calculate 
    aggfunc=['max','min','mean']  #avg
)

print(result)

              max    min     mean
           salary salary   salary
department
DE          70000  50000  60000.0
HR          45000  45000  45000.0
QA          50000  40000  45000.0

In [38]:
dataM = {
    "empid": [101, 102, 103],
    "Jan": [100, 200, 300],
    "Feb": [150, 250, 350],
    "Mar": [200, 300, 400]
}
df = pd.DataFrame(dataM)
df

   empid  Jan  Feb  Mar
0    101  100  150  200
1    102  200  250  300
2    103  300  350  400

In [41]:
result =df.melt(
    id_vars='empid',  #column you keep fixed
    var_name='month',  #name for the old column names
    value_name='sales' #name for the values
    
)
print(result)

   empid  moh  sales
0    101  Jan    100
1    102  Jan    200
2    103  Jan    300
3    101  Feb    150
4    102  Feb    250
5    103  Feb    350
6    101  Mar    200
7    102  Mar    300
8    103  Mar    400

In [44]:
df=pd.DataFrame(result)
df

   empid  moh  sales
0    101  Jan    100
1    102  Jan    200
2    103  Jan    300
3    101  Feb    150
4    102  Feb    250
5    103  Feb    350
6    101  Mar    200
7    102  Mar    300
8    103  Mar    400

In [49]:
total_sales =result.groupby('empid')['sales'].sum()
print(total_sales)

empid
101     450
102     750
103    1050
Name: sales, dtype: int64