In [3]:
import pandas as pd

In [9]:

employees = pd.DataFrame({
    "empid": [101, 102, 103, 104],
    "ename": ["Amey", "Raj", "Amit", "Suresh"]
})

df1 = pd.DataFrame(employees)
df1

   empid   ename
0    101    Amey
1    102     Raj
2    103    Amit
3    104  Suresh

In [10]:

salary = pd.DataFrame({
    "empid": [101, 102, 103, 105],
    "sal": [50000, 60000, 70000, 80000]
})
df2=pd.DataFrame(salary)
df2

   empid    sal
0    101  50000
1    102  60000
2    103  70000
3    105  80000

In [13]:
df3=pd.merge(employees,salary, on='empid',how='inner')
df3

   empid ename    sal
0    101  Amey  50000
1    102   Raj  60000
2    103  Amit  70000

In [14]:
df4=pd.merge(employees,salary,on='empid',how='left')
df4

   empid   ename      sal
0    101    Amey  50000.0
1    102     Raj  60000.0
2    103    Amit  70000.0
3    104  Suresh      NaN

In [17]:
df5=pd.merge(employees,salary,on='empid',how='outer',indicator=True)
df5

   empid   ename      sal      _merge
0    101    Amey  50000.0        both
1    102     Raj  60000.0        both
2    103    Amit  70000.0        both
3    104  Suresh      NaN   left_only
4    105     NaN  80000.0  right_only

In [29]:
df2.rename(columns={'empid':'employee_id'},inplace=True)
df2

   employee_id    sal
0          101  50000
1          102  60000
2          103  70000
3          105  80000

In [33]:
df6=pd.merge(df1,df2,left_on='empid',right_on='employee_id')
df6

   empid ename  employee_id    sal
0    101  Amey          101  50000
1    102   Raj          102  60000
2    103  Amit          103  70000

In [36]:
data = {
    "department": ["DE", "DE", "QA", "QA"],
    "year": [2024, 2025, 2024, 2025],
    "salary": [50000, 60000, 45000, 55000]
}

df=pd.DataFrame(data)
df

  department  year  salary
0         DE  2024   50000
1         DE  2025   60000
2         QA  2024   45000
3         QA  2025   55000

In [37]:
#multiindex
df.set_index(['department','year'])

                 salary
department year
DE         2024   50000
           2025   60000
QA         2024   45000
           2025   55000

In [40]:
df[df['department']== 'DE']

  department  year  salary
0         DE  2024   50000
1         DE  2025   60000

In [42]:
df[(df['department']== 'DE')&(df['year']==2025)]

  department  year  salary
1         DE  2025   60000

In [44]:
df.reset_index()

   index department  year  salary
0      0         DE  2024   50000
1      1         DE  2025   60000
2      2         QA  2024   45000
3      3         QA  2025   55000

In [45]:
df = pd.DataFrame({
    "month": ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    "sales": [100, 200, 150, 300, 250, 400]
})
df

  month  sales
0   Jan    100
1   Feb    200
2   Mar    150
3   Apr    300
4   May    250
5   Jun    400

In [53]:
df['previous_month_sales']=df['sales'].shift(1)
df['previous_month_sales']
df

  month  sales  previous_month_sales
0   Jan    100                   NaN
1   Feb    200                 100.0
2   Mar    150                 200.0
3   Apr    300                 150.0
4   May    250                 300.0
5   Jun    400                 250.0

In [54]:
df['sales_change']= df['sales']-df['previous_month_sales']
df

  month  sales  previous_month_sales  sales_change
0   Jan    100                   NaN           NaN
1   Feb    200                 100.0         100.0
2   Mar    150                 200.0         -50.0
3   Apr    300                 150.0         150.0
4   May    250                 300.0         -50.0
5   Jun    400                 250.0         150.0

In [55]:
df['3_month_avg']= df['sales'].rolling(3).mean()

In [62]:
df

,month,sales,previous_month_sales,sales_change,3_month_avg,running_total,running_avg
0,Jan,100,NaN,NaN,NaN,100,100.000000
1,Feb,200,100.0,100.0,NaN,300,150.000000
2,Mar,150,200.0,-50.0,150.000000,450,150.000000
3,Apr,300,150.0,150.0,216.666667,750,187.500000
4,May,250,300.0,-50.0,233.333333,1000,200.000000
5,Jun,400,250.0,150.0,316.666667,1400,233.333333

In [57]:
df['running_total']=df['sales'].cumsum()

In [61]:
df['running_avg']=df['sales'].expanding().mean()