In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv("E:/py/datasets1/empdata.csv")
df

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [6]:
df['annual_salary']=df['sal']*12
df

   empid           ename       sal         doj  annual_salary
0   1001      Ganesh Rao  10000.00  2000-10-10      120000.00
1   1002      Anil Kumar  23000.50  2002-03-03      276006.00
2   1003    Gaurav Gupta  18000.33  2002-03-03      216003.96
3   1004    Hema Chandra  16500.50  2002-03-03      198006.00
4   1005  Laxmi Prasanna  12000.75  2000-08-10      144009.00
5   1006       Anant Nag   9999.99  1999-09-09      119999.88

In [15]:
import numpy as np

df['salary_status'] = np.where(
    df['sal'] > 20000,
    "high",
    "low"
)

df['salary_status']

0     low
1    high
2     low
3     low
4     low
5     low
Name: salary_status, dtype: object

In [24]:
df

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [27]:
categories = [
    df['sal'] >= 25000,
    df['sal'] >= 15000,
    df['sal'] <= 14000
]

choices = [
    'high',
    'medium',
    'low'
]

df['salary_category'] = np.select(categories, choices,default='unknown')

df

   empid           ename       sal         doj salary_category
0   1001      Ganesh Rao  10000.00  2000-10-10             low
1   1002      Anil Kumar  23000.50  2002-03-03          medium
2   1003    Gaurav Gupta  18000.33  2002-03-03          medium
3   1004    Hema Chandra  16500.50  2002-03-03          medium
4   1005  Laxmi Prasanna  12000.75  2000-08-10             low
5   1006       Anant Nag   9999.99  1999-09-09             low

In [36]:
#Convert names to uppercase. Calculate name length.
#Find names containing "a" irrespective of case. ind names starting with "A".

df['ename'].str.upper()
df['ename'].str.len()
df['ename'].str.contains('a',case=False)
df['ename'].str.startswith('A')

0    False
1     True
2    False
3    False
4    False
5     True
Name: ename, dtype: bool

In [38]:
df['sal'].value_counts()

sal
10000.00    1
23000.50    1
18000.33    1
16500.50    1
12000.75    1
9999.99     1
Name: count, dtype: int64

In [39]:
df['sal'].unique()

array([10000.  , 23000.5 , 18000.33, 16500.5 , 12000.75,  9999.99])

In [40]:
df['sal'].nunique()

6

In [41]:
df = pd.DataFrame({
    "empid": [101, 102, 103],
    "skills": [
        ["Python", "SQL"],
        ["Python", "Snowflake"],
        ["SQL", "AWS", "Python"]
    ]
})

In [43]:
df.explode('skills')

   empid     skills
0    101     Python
0    101        SQL
1    102     Python
1    102  Snowflake
2    103        SQL
2    103        AWS
2    103     Python

In [44]:
df['skills'].value_counts()

skills
[Python, SQL]          1
[Python, Snowflake]    1
[SQL, AWS, Python]     1
Name: count, dtype: int64

In [46]:
df['skills'].value_counts()

skills
[Python, SQL]          1
[Python, Snowflake]    1
[SQL, AWS, Python]     1
Name: count, dtype: int64

In [47]:
import pandas as pd

f = pd.DataFrame({
    "empid": [101, 102, 103],
    "skills": [
        ["Python", "SQL"],
        ["Python", "Snowflake"],
        ["SQL", "AWS", "Python"]
    ]
})

print(f)

   empid               skills
0    101        [Python, SQL]
1    102  [Python, Snowflake]
2    103   [SQL, AWS, Python]

In [48]:
f1 = f.explode('skills')

print(f1)

   empid     skills
0    101     Python
0    101        SQL
1    102     Python
1    102  Snowflake
2    103        SQL
2    103        AWS
2    103     Python

In [49]:
print(f1['skills'].value_counts())

skills
Python       3
SQL          2
Snowflake    1
AWS          1
Name: count, dtype: int64

In [52]:
import pandas as pd

df = pd.DataFrame({
    "date": pd.date_range("2025-01-01", periods=10),
    "sales": [100, 150, 120, 180, 200, 250, 220, 300, 280, 350]
})

df

        date  sales
0 2025-01-01    100
1 2025-01-02    150
2 2025-01-03    120
3 2025-01-04    180
4 2025-01-05    200
5 2025-01-06    250
6 2025-01-07    220
7 2025-01-08    300
8 2025-01-09    280
9 2025-01-10    350

In [70]:
df['prv_sales']=df['sales'].shift(1)
df

,date,sales,prv_sales,sales_difference,moving_avg,moving_max,moving_min,running_total,running_avg,ewm_avg,growth_perc
0,2025-01-01,100,NaN,NaN,NaN,NaN,NaN,100.0,100.000000,100.000000,NaN
1,2025-01-02,150,100.0,50.0,NaN,NaN,NaN,250.0,125.000000,133.333333,50.0
2,2025-01-03,120,150.0,-30.0,123.333333,150.0,100.0,370.0,123.333333,125.714286,20.0
3,2025-01-04,180,120.0,60.0,150.000000,180.0,120.0,550.0,137.500000,154.666667,80.0
4,2025-01-05,200,180.0,20.0,166.666667,200.0,120.0,750.0,150.000000,178.064516,100.0
5,2025-01-06,250,200.0,50.0,210.000000,250.0,180.0,1000.0,166.666667,214.603175,150.0
6,2025-01-07,220,250.0,-30.0,223.333333,250.0,200.0,1220.0,174.285714,217.322835,120.0
7,2025-01-08,300,220.0,80.0,256.666667,300.0,220.0,1520.0,190.000000,258.823529,200.0
8,2025-01-09,280,300.0,-20.0,266.666667,300.0,220.0,1800.0,200.000000,269.432485,180.0
9,2025-01-10,350,280.0,70.0,310.000000,350.0,280.0,2150.0,215.000000,309.755621,250.0

In [55]:
df['sales_difference']= df['sales']-df['prv_sales']

In [57]:
df['moving_avg']=df['sales'].rolling(3).mean()

In [59]:
df['moving_max']=df['sales'].rolling(3).max()

In [60]:
df['moving_min']=df['sales'].rolling(3).min()

In [62]:
df['running_total']=df['sales'].expanding().sum()

In [65]:
df['running_avg']=df['sales'].expanding().mean()

# EXPONENTIALLY WEIGHTED MEAN() ewm()

In [67]:
df['ewm_avg']=df['sales'].ewm(span=3).mean()

In [69]:
df['growth_perc']= df['sales']-df['prv_sales']/df['prv_sales']* 100

# timefunction

In [101]:
import pandas as pd

df = pd.DataFrame({
    "date": pd.date_range("2025-01-01", periods=90, freq="D"),
    "sales": range(100, 190)
})

df

         date  sales
0  2025-01-01    100
1  2025-01-02    101
2  2025-01-03    102
3  2025-01-04    103
4  2025-01-05    104
..        ...    ...
85 2025-03-27    185
86 2025-03-28    186
87 2025-03-29    187
88 2025-03-30    188
89 2025-03-31    189

[90 rows x 2 columns]

In [102]:
df['date']=pd.to_datetime(df['date'])

In [103]:
df['date']

0    2025-01-01
1    2025-01-02
2    2025-01-03
3    2025-01-04
4    2025-01-05
        ...
85   2025-03-27
86   2025-03-28
87   2025-03-29
88   2025-03-30
89   2025-03-31
Name: date, Length: 90, dtype: datetime64[ns]

In [104]:
df['year']=df['date'].dt.year
df['month']=df['date'].dt.month
df['day']=df['date'].dt.day
df['day_name']=df['date'].dt.day_name()
df['quarter']=df['date'].dt.quarter

In [78]:
df

         date  sales  year  month  day   day_name  quarter
0  2025-01-01    100  2025      1    1  Wednesday        1
1  2025-01-02    101  2025      1    2   Thursday        1
2  2025-01-03    102  2025      1    3     Friday        1
3  2025-01-04    103  2025      1    4   Saturday        1
4  2025-01-05    104  2025      1    5     Sunday        1
..        ...    ...   ...    ...  ...        ...      ...
85 2025-03-27    185  2025      3   27   Thursday        1
86 2025-03-28    186  2025      3   28     Friday        1
87 2025-03-29    187  2025      3   29   Saturday        1
88 2025-03-30    188  2025      3   30     Sunday        1
89 2025-03-31    189  2025      3   31     Monday        1

[90 rows x 7 columns]

In [81]:
df[df['date']>='2025-02-01']

         date  sales  year  month  day   day_name  quarter
31 2025-02-01    131  2025      2    1   Saturday        1
32 2025-02-02    132  2025      2    2     Sunday        1
33 2025-02-03    133  2025      2    3     Monday        1
34 2025-02-04    134  2025      2    4    Tuesday        1
35 2025-02-05    135  2025      2    5  Wednesday        1
36 2025-02-06    136  2025      2    6   Thursday        1
37 2025-02-07    137  2025      2    7     Friday        1
38 2025-02-08    138  2025      2    8   Saturday        1
39 2025-02-09    139  2025      2    9     Sunday        1
40 2025-02-10    140  2025      2   10     Monday        1
41 2025-02-11    141  2025      2   11    Tuesday        1
42 2025-02-12    142  2025      2   12  Wednesday        1
43 2025-02-13    143  2025      2   13   Thursday        1
44 2025-02-14    144  2025      2   14     Friday        1
45 2025-02-15    145  2025      2   15   Saturday        1
46 2025-02-16    146  2025      2   16     Sunday        1
47 2025-02-17    147  2025      2   17     Monday        1
48 2025-02-18    148  2025      2   18    Tuesday        1
49 2025-02-19    149  2025      2   19  Wednesday        1
50 2025-02-20    150  2025      2   20   Thursday        1
51 2025-02-21    151  2025      2   21     Friday        1
52 2025-02-22    152  2025      2   22   Saturday        1
53 2025-02-23    153  2025      2   23     Sunday        1
54 2025-02-24    154  2025      2   24     Monday        1
55 2025-02-25    155  2025      2   25    Tuesday        1
56 2025-02-26    156  2025      2   26  Wednesday        1
57 2025-02-27    157  2025      2   27   Thursday        1
58 2025-02-28    158  2025      2   28     Friday        1
59 2025-03-01    159  2025      3    1   Saturday        1
60 2025-03-02    160  2025      3    2     Sunday        1
61 2025-03-03    161  2025      3    3     Monday        1
62 2025-03-04    162  2025      3    4    Tuesday        1
63 2025-03-05    163  2025      3    5  Wednesday        1
64 2025-03-06    164  2025      3    6   Thursday        1
65 2025-03-07    165  2025      3    7     Friday        1
66 2025-03-08    166  2025      3    8   Saturday        1
67 2025-03-09    167  2025      3    9     Sunday        1
68 2025-03-10    168  2025      3   10     Monday        1
69 2025-03-11    169  2025      3   11    Tuesday        1
70 2025-03-12    170  2025      3   12  Wednesday        1
71 2025-03-13    171  2025      3   13   Thursday        1
72 2025-03-14    172  2025      3   14     Friday        1
73 2025-03-15    173  2025      3   15   Saturday        1
74 2025-03-16    174  2025      3   16     Sunday        1
75 2025-03-17    175  2025      3   17     Monday        1
76 2025-03-18    176  2025      3   18    Tuesday        1
77 2025-03-19    177  2025      3   19  Wednesday        1
78 2025-03-20    178  2025      3   20   Thursday        1
79 2025-03-21    179  2025      3   21     Friday        1
80 2025-03-22    180  2025      3   22   Saturday        1
81 2025-03-23    181  2025      3   23     Sunday        1
82 2025-03-24    182  2025      3   24     Monday        1
83 2025-03-25    183  2025      3   25    Tuesday        1
84 2025-03-26    184  2025      3   26  Wednesday        1
85 2025-03-27    185  2025      3   27   Thursday        1
86 2025-03-28    186  2025      3   28     Friday        1
87 2025-03-29    187  2025      3   29   Saturday        1
88 2025-03-30    188  2025      3   30     Sunday        1
89 2025-03-31    189  2025      3   31     Monday        1

In [105]:
df

         date  sales  year  month  day   day_name  quarter
0  2025-01-01    100  2025      1    1  Wednesday        1
1  2025-01-02    101  2025      1    2   Thursday        1
2  2025-01-03    102  2025      1    3     Friday        1
3  2025-01-04    103  2025      1    4   Saturday        1
4  2025-01-05    104  2025      1    5     Sunday        1
..        ...    ...   ...    ...  ...        ...      ...
85 2025-03-27    185  2025      3   27   Thursday        1
86 2025-03-28    186  2025      3   28     Friday        1
87 2025-03-29    187  2025      3   29   Saturday        1
88 2025-03-30    188  2025      3   30     Sunday        1
89 2025-03-31    189  2025      3   31     Monday        1

[90 rows x 7 columns]

In [106]:
df = df.set_index('date')

monthly_sales = df['sales'].resample('ME').sum()

print(monthly_sales)

date
2025-01-31    3565
2025-02-28    4046
2025-03-31    5394
Freq: ME, Name: sales, dtype: int64

In [107]:
monthly_sales_avg = df['sales'].resample('ME').mean()

print(monthly_sales_avg)

date
2025-01-31    115.0
2025-02-28    144.5
2025-03-31    174.0
Freq: ME, Name: sales, dtype: float64

In [109]:
Calculate_monthly =df['sales'].resample('ME').agg(['sum','mean','max','min'])
print(Calculate_monthly)

             sum   mean  max  min
date
2025-01-31  3565  115.0  130  100
2025-02-28  4046  144.5  158  131
2025-03-31  5394  174.0  189  159

In [110]:
quarter_sales= df['sales'].resample('QE').agg(sum)
print(quarter_sales)

date
2025-03-31    13005
Freq: QE-DEC, Name: sales, dtype: int64

C:\Users\Amey\AppData\Local\Temp\ipykernel_31696\2694905779.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DatetimeIndexResampler.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  quarter_sales= df['sales'].resample('QE').agg(sum)

In [111]:
weekly_sales = df['sales'].resample('W').sum()
print(weekly_sales)

date
2025-01-05     510
2025-01-12     756
2025-01-19     805
2025-01-26     854
2025-02-02     903
2025-02-09     952
2025-02-16    1001
2025-02-23    1050
2025-03-02    1099
2025-03-09    1148
2025-03-16    1197
2025-03-23    1246
2025-03-30    1295
2025-04-06     189
Freq: W-SUN, Name: sales, dtype: int64

In [115]:
WEEKLY_DAYS = pd.date_range(
    start="2025-01-01",   # not startS
    periods=7,
    freq="D"
)

print(WEEKLY_DAYS)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07'],
              dtype='datetime64[ns]', freq='D')

In [116]:
df = pd.DataFrame({
    "date": WEEKLY_DAYS
})

In [117]:
df["date_after_7_days"] = df["date"] + pd.Timedelta(days=7)

In [118]:
df["date_after_7_days"]

0   2025-01-08
1   2025-01-09
2   2025-01-10
3   2025-01-11
4   2025-01-12
5   2025-01-13
6   2025-01-14
Name: date_after_7_days, dtype: datetime64[ns]